name = "grammy"
version = "0.3.2"

description = "A basic Gleam UDP server"
licences = ["Apache-2.0"]
repository = { type = "github", user = "rawhat", repo = "grammy" }
# links = [{ title = "Website", href = "https://gleam.run" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
gleam_otp = "1.0.0-rc3"
gleam_erlang = "1.0.0-rc1"
logging = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.3.1 and < 2.0.0"
